name: sp2_env
channels:
        - conda-forge
        - defaults
dependencies:
        - xarray
        - act-atmos
        - scipy
        - pandas
        - xlrd
        - numba
        - matplotlib
        - python>=3.7
