name: pysp2-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - act-atmos
  - xarray
  - sphinx
  - pydata-sphinx-theme
  - pip:
      - sphinx_gallery
      - sphinx-copybutton
      - sphinx_design
      - nbsphinx
      - sphinxcontrib-applehelp<1.0.8
