name: pysp2-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - act-atmos
  - xarray
  - pip:
      - sphinx
      - sphinx_gallery
      - sphinx-copybutton
      - pydata-sphinx-theme
      - sphinxcontrib-applehelp<1.0.8
      - sphinxcontrib-devhelp<1.0.6
      - sphinx_design
      - nbsphinx
